version: "3.7"

services:
  gitdb:
    image: rudl/gitdb:unstable
    environment:
      GIT_REPO_URL: git@PUT_YOUR_GIT_SSH_CLONE/URL/HERE.git
      GIT_REPO_SSH_KEY: "file:/var/run/secrets/rudldb_ssh_key"
      RUDL_VAULT_SECRET: "file:/var/run/secrets/rudldb_vault_secret"
    deploy:
      placement:
        constraints: [ node.role == manager ]
    volumes:
      - "gitdbvol:/data"
    networks:
      - ingress-net
    secrets:
      - rudldb_vault_secret
      - rudldb_ssh_key

  ingress-nginx:
    image: rudl/ingress-nginx:unstable
    deploy:
      mode: global
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    environment:
      RUDL_GITDB_URL: "http://gitdb"
      RUDL_GITDB_CLIENT_ID: ingress1
      RUDL_GITDB_CLIENT_SECRET: "file:/var/run/secrets/ingress1_client_secret"
      INGRESS_SCOPE: ingress
      INGRESS_OBJECT_NAME: ingress1.yml
      SSL_CERT_SCOPE: ssl_certs
      SSL_CERT_ISSUER_URL: http://cert-issuer
    networks:
      - ingress-net
    secrets:
      - ingress1_client_secret

  cert-issuer:
    image: rudl/cert-issuer:unstable
    environment:
      RUDL_GITDB_URL: http://gitdb
      RUDL_GITDB_CLIENT_ID: issuer1
      RUDL_GITDB_CLIENT_SECRET: "file:/var/run/secrets/issuer1_client_secret"
      SSL_CERT_SCOPE: ssl_certs
      CERT_REQ_OBJECT: issuer.conf.yml
      TOS_EMAIL: "your@email.xy"
    networks:
      - ingress-net
    secrets:
      - issuer1_client_secret

  agent-swarm:
    image: rudl/agent-swarm:unstable
    deploy:
      placement:
        constraints: [ node.role == manager ]
    environment:
      RUDL_GITDB_URL: http://gitdb
      RUDL_GITDB_CLIENT_ID: swarm1
      RUDL_GITDB_CLIENT_SECRET: "file:/var/run/secrets/swarm1_client_secret"
      SWARM_SCOPE: cluster1
      SWARM_CONF_OBJECT: swarm.conf.yml
    secrets:
      - swarm1_client_secret
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"


volumes:
  gitdbvol:

secrets:
  rudldb_vault_secret:
    external: true
  rudldb_ssh_key:
    external: true
  ingress1_client_secret:
    external: true
  issuer1_client_secret:
    external: true
  swarm1_client_secret:
    external: true

networks:
  ingress-net:
    name: ingress-net
